In [2]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [3]:
# Get element [r, c]
a[1,5]

13

In [4]:
# Get row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# Get column
a[:, 2]

array([ 3, 10])

In [6]:
# Get fancy things [starting index:ending index:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [7]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [8]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [9]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
