In [46]:
import numpy as np
a = np.array([1,2,3,4])
# https://numpy.org/doc/stable/reference/routines.math.html
# https://numpy.org/doc/stable/reference/routines.linalg.html

In [19]:
a + 2

array([3, 4, 5, 6])

In [20]:
a - 2 

array([-1,  0,  1,  2])

In [21]:
a * 2

array([2, 4, 6, 8])

In [22]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [24]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [26]:
a ** 2

array([ 1,  4,  9, 16])

In [30]:
# sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [32]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [39]:
a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [47]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [49]:
stats = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
stats

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [54]:
np.min(stats, axis=1)

array([1, 8])

In [58]:
np.max(stats, axis=1)

array([ 7, 14])

In [62]:
np.sum(stats, axis=1)

array([28, 77])

In [63]:
np.sum(stats, axis=0)

array([ 9, 11, 13, 15, 17, 19, 21])