In [3]:
import numpy as np

In [10]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedate = filedata.astype('int32')

In [19]:
filt = filedata > 50
filedata[filt]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [20]:
# U can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [25]:
np.any(filedata > 50, axis=0)

array([ True,  True,  True])

In [28]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [34]:
~(((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])