In [2]:
import numpy as np
before = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [18]:
after = before.reshape((7,2))
after

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [22]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4,5,6,7])
v2 = np.array([8,9,10,11,12,13,14])

np.vstack([v1,v2,v2])

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [25]:
# Horizonatl stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])