In [2]:
import numpy as np

In [3]:
# All 0s matrix
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [4]:
# All 1s metrix

In [5]:
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [6]:
# any other numbers
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [7]:
# Any other number (full like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full(a.shape, 4) 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [8]:
# Random decimal numbers
np.random.rand(2,3,5)

array([[[0.90547574, 0.17115816, 0.13284085, 0.22566557, 0.9041814 ],
        [0.58934115, 0.34592864, 0.62604262, 0.88253856, 0.8268075 ],
        [0.55847597, 0.68989582, 0.46548476, 0.85595398, 0.69096037]],

       [[0.60762895, 0.60097975, 0.35208963, 0.92415031, 0.43946469],
        [0.16178892, 0.85220772, 0.26053696, 0.67066788, 0.77657002],
        [0.38756681, 0.49765243, 0.73987954, 0.46221685, 0.62746564]]])

In [9]:
# random but with tuple
np.random.random_sample((1,2))

array([[0.2560735 , 0.99567741]])

In [10]:
# Random int numbers
np.random.randint(6, 10, size=(3,3))

array([[8, 9, 8],
       [7, 8, 9],
       [8, 7, 7]])

In [11]:
# The identity martix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Reaeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [13]:
c = np.zeros((11,11))
c[:, 0] = 1
c[:, -1] = 1
c[0, :] = 1
c[-1, :] = 1
c[5,5] = 9
c


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 9., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
a = np.array([1,2,3])
b = a
b[0] = 100
a

array([100,   2,   3])

In [21]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
b

array([100,   2,   3])