In [1]:
import numpy as np

In [7]:
# All 0s matrix
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [9]:
# All 1s metrix

In [16]:
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [19]:
# any other numbers
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [24]:
# Any other number (full like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full(a.shape, 4) 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(2,3,5)

array([[[0.51205137, 0.13934172, 0.0496983 , 0.24134406, 0.59048779],
        [0.50637715, 0.59375964, 0.66546213, 0.13779654, 0.82265474],
        [0.70612769, 0.57601191, 0.91412539, 0.96337278, 0.11238717]],

       [[0.75846259, 0.93636528, 0.24257996, 0.91734371, 0.43061816],
        [0.39919116, 0.54704279, 0.12349237, 0.41197595, 0.99442673],
        [0.49954228, 0.69875626, 0.53181384, 0.34258951, 0.12424748]]])

In [31]:
# random but with tuple
np.random.random_sample((1,2))

array([[0.11792514, 0.6194563 ]])

In [63]:
# Random int numbers
np.random.randint(6, 10, size=(3,3))

array([[9, 9, 7],
       [6, 9, 9],
       [9, 8, 6]])

In [65]:
# The identity martix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
# Reaeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [92]:
c = np.zeros((11,11))
c[:, 0] = 1
c[:, len(c)-1] = 1
c[0, :] = 1
c[len(c)-1, :] = 1
c[5,5] = 9
c


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 9., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [93]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])